# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(770, 539)
        self.qb_a = QtWidgets.QPushButton(Form)
        self.qb_a.setGeometry(QtCore.QRect(150, 410, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_a.setFont(font)
        self.qb_a.setObjectName("qb_a")
        self.lb_cabeca = QtWidgets.QLabel(Form)
        self.lb_cabeca.setGeometry(QtCore.QRect(397.5, 100, 54, 70))
        self.lb_cabeca.setText("")
        self.lb_cabeca.setObjectName("lb_cabeca")
        self.qb_w = QtWidgets.QPushButton(Form)
        self.qb_w.setGeometry(QtCore.QRect(190, 360, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_w.setFont(font)
        self.qb_w.setObjectName("qb_w")
        self.pb_q = QtWidgets.QPushButton(Form)
        self.pb_q.setGeometry(QtCore.QRect(140, 360, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_q.setFont(font)
        self.pb_q.setObjectName("pb_q")
        self.qb_z = QtWidgets.QPushButton(Form)
        self.qb_z.setGeometry(QtCore.QRect(160, 460, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_z.setFont(font)
        self.qb_z.setObjectName("qb_z")
        self.qb_s = QtWidgets.QPushButton(Form)
        self.qb_s.setGeometry(QtCore.QRect(200, 410, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_s.setFont(font)
        self.qb_s.setObjectName("qb_s")
        self.qb_x = QtWidgets.QPushButton(Form)
        self.qb_x.setGeometry(QtCore.QRect(210, 460, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_x.setFont(font)
        self.qb_x.setObjectName("qb_x")
        self.qb_e = QtWidgets.QPushButton(Form)
        self.qb_e.setGeometry(QtCore.QRect(240, 360, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_e.setFont(font)
        self.qb_e.setObjectName("qb_e")
        self.qb_r = QtWidgets.QPushButton(Form)
        self.qb_r.setGeometry(QtCore.QRect(290, 360, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_r.setFont(font)
        self.qb_r.setObjectName("qb_r")
        self.qb_t = QtWidgets.QPushButton(Form)
        self.qb_t.setGeometry(QtCore.QRect(340, 360, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_t.setFont(font)
        self.qb_t.setObjectName("qb_t")
        self.qb_y = QtWidgets.QPushButton(Form)
        self.qb_y.setGeometry(QtCore.QRect(390, 360, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_y.setFont(font)
        self.qb_y.setObjectName("qb_y")
        self.qb_u = QtWidgets.QPushButton(Form)
        self.qb_u.setGeometry(QtCore.QRect(440, 360, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_u.setFont(font)
        self.qb_u.setObjectName("qb_u")
        self.qb_i = QtWidgets.QPushButton(Form)
        self.qb_i.setGeometry(QtCore.QRect(490, 360, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_i.setFont(font)
        self.qb_i.setObjectName("qb_i")
        self.qb_d = QtWidgets.QPushButton(Form)
        self.qb_d.setGeometry(QtCore.QRect(250, 410, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_d.setFont(font)
        self.qb_d.setObjectName("qb_d")
        self.qb_o = QtWidgets.QPushButton(Form)
        self.qb_o.setGeometry(QtCore.QRect(540, 360, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_o.setFont(font)
        self.qb_o.setObjectName("qb_o")
        self.qb_p = QtWidgets.QPushButton(Form)
        self.qb_p.setGeometry(QtCore.QRect(590, 360, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_p.setFont(font)
        self.qb_p.setObjectName("qb_p")
        self.qb_f = QtWidgets.QPushButton(Form)
        self.qb_f.setGeometry(QtCore.QRect(300, 410, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_f.setFont(font)
        self.qb_f.setObjectName("qb_f")
        self.qb_g = QtWidgets.QPushButton(Form)
        self.qb_g.setGeometry(QtCore.QRect(350, 410, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_g.setFont(font)
        self.qb_g.setObjectName("qb_g")
        self.qb_h = QtWidgets.QPushButton(Form)
        self.qb_h.setGeometry(QtCore.QRect(400, 410, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_h.setFont(font)
        self.qb_h.setObjectName("qb_h")
        self.qb_j = QtWidgets.QPushButton(Form)
        self.qb_j.setGeometry(QtCore.QRect(450, 410, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_j.setFont(font)
        self.qb_j.setObjectName("qb_j")
        self.qb_k = QtWidgets.QPushButton(Form)
        self.qb_k.setGeometry(QtCore.QRect(500, 410, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_k.setFont(font)
        self.qb_k.setObjectName("qb_k")
        self.qb_l = QtWidgets.QPushButton(Form)
        self.qb_l.setGeometry(QtCore.QRect(550, 410, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_l.setFont(font)
        self.qb_l.setObjectName("qb_l")
        self.qb_cc = QtWidgets.QPushButton(Form)
        self.qb_cc.setGeometry(QtCore.QRect(600, 410, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_cc.setFont(font)
        self.qb_cc.setObjectName("qb_cc")
        self.qb_b = QtWidgets.QPushButton(Form)
        self.qb_b.setGeometry(QtCore.QRect(360, 460, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_b.setFont(font)
        self.qb_b.setObjectName("qb_b")
        self.qb_c = QtWidgets.QPushButton(Form)
        self.qb_c.setGeometry(QtCore.QRect(260, 460, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_c.setFont(font)
        self.qb_c.setObjectName("qb_c")
        self.qb_v = QtWidgets.QPushButton(Form)
        self.qb_v.setGeometry(QtCore.QRect(310, 460, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_v.setFont(font)
        self.qb_v.setObjectName("qb_v")
        self.qb_m = QtWidgets.QPushButton(Form)
        self.qb_m.setGeometry(QtCore.QRect(460, 460, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_m.setFont(font)
        self.qb_m.setObjectName("qb_m")
        self.qb_n = QtWidgets.QPushButton(Form)
        self.qb_n.setGeometry(QtCore.QRect(410, 460, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.qb_n.setFont(font)
        self.qb_n.setObjectName("qb_n")
        self.lb_corpo = QtWidgets.QLabel(Form)
        self.lb_corpo.setGeometry(QtCore.QRect(424, 170, 2, 55))
        self.lb_corpo.setText("")
        self.lb_corpo.setObjectName("lb_corpo")
        self.lb_forca = QtWidgets.QLabel(Form)
        self.lb_forca.setGeometry(QtCore.QRect(270, 10, 191, 291))
        self.lb_forca.setText("")
        self.lb_forca.setObjectName("lb_forca")
        self.lb_bracoesquerdo = QtWidgets.QLabel(Form)
        self.lb_bracoesquerdo.setGeometry(QtCore.QRect(378, 165, 44, 20))
        self.lb_bracoesquerdo.setText("")
        self.lb_bracoesquerdo.setObjectName("lb_bracoesquerdo")
        self.lb_bracodireito = QtWidgets.QLabel(Form)
        self.lb_bracodireito.setGeometry(QtCore.QRect(427, 165, 44, 20))
        self.lb_bracodireito.setText("")
        self.lb_bracodireito.setObjectName("lb_bracodireito")
        self.lb_pernaesquerda = QtWidgets.QLabel(Form)
        self.lb_pernaesquerda.setGeometry(QtCore.QRect(400, 220, 25, 50))
        self.lb_pernaesquerda.setText("")
        self.lb_pernaesquerda.setObjectName("lb_pernaesquerda")
        self.lb_pernadireita = QtWidgets.QLabel(Form)
        self.lb_pernadireita.setGeometry(QtCore.QRect(425, 220, 25, 50))
        self.lb_pernadireita.setText("")
        self.lb_pernadireita.setObjectName("lb_pernadireita")
        self.lb_forca.raise_()
        self.qb_a.raise_()
        self.lb_cabeca.raise_()
        self.qb_w.raise_()
        self.pb_q.raise_()
        self.qb_z.raise_()
        self.qb_s.raise_()
        self.qb_x.raise_()
        self.qb_e.raise_()
        self.qb_r.raise_()
        self.qb_t.raise_()
        self.qb_y.raise_()
        self.qb_u.raise_()
        self.qb_i.raise_()
        self.qb_d.raise_()
        self.qb_o.raise_()
        self.qb_p.raise_()
        self.qb_f.raise_()
        self.qb_g.raise_()
        self.qb_h.raise_()
        self.qb_j.raise_()
        self.qb_k.raise_()
        self.qb_l.raise_()
        self.qb_cc.raise_()
        self.qb_b.raise_()
        self.qb_c.raise_()
        self.qb_v.raise_()
        self.qb_m.raise_()
        self.qb_n.raise_()
        self.lb_corpo.raise_()
        self.lb_bracoesquerdo.raise_()
        self.lb_bracodireito.raise_()
        self.lb_pernaesquerda.raise_()
        self.lb_pernadireita.raise_()

        self.cabeca = QPixmap("cabeca.png")
        self.cabeca = self.cabeca.scaled(self.lb_cabeca.frameGeometry().width(),self.lb_cabeca.frameGeometry().height())
        self.lb_cabeca.setPixmap(self.cabeca)

        self.corpo = QPixmap("corpo.png")
        self.corpo = self.corpo.scaled(self.lb_corpo.frameGeometry().width(),self.lb_corpo.frameGeometry().height())
        self.lb_corpo.setPixmap(self.corpo)

        self.forca = QPixmap("forca.png")
        self.forca = self.forca.scaled(self.lb_forca.frameGeometry().width(),self.lb_forca.frameGeometry().height())
        self.lb_forca.setPixmap(self.forca)

        self.bracoesquerdo = QPixmap("braco esquerdo.png")
        self.bracoesquerdo = self.bracoesquerdo.scaled(self.lb_bracoesquerdo.frameGeometry().width(),self.lb_bracoesquerdo.frameGeometry().height())
        self.lb_bracoesquerdo.setPixmap(self.bracoesquerdo)

        self.bracodireito = QPixmap("braco direito.png")
        self.bracodireito = self.bracodireito.scaled(self.lb_bracodireito.frameGeometry().width(),self.lb_bracodireito.frameGeometry().height())
        self.lb_bracodireito.setPixmap(self.bracodireito)

        self.pernaesquerda = QPixmap("perna esquerda.png")
        self.pernaesquerda = self.pernaesquerda.scaled(self.lb_pernaesquerda.frameGeometry().width(),self.lb_pernaesquerda.frameGeometry().height())
        self.lb_pernaesquerda.setPixmap(self.pernaesquerda)

        self.pernadireita = QPixmap("perna direita.png")
        self.pernadireita = self.pernadireita.scaled(self.lb_pernadireita.frameGeometry().width(),self.lb_pernadireita.frameGeometry().height())
        self.lb_pernadireita.setPixmap(self.pernadireita)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.qb_a.setText(_translate("Form", "A"))
        self.qb_w.setText(_translate("Form", "W"))
        self.pb_q.setText(_translate("Form", "Q"))
        self.qb_z.setText(_translate("Form", "Z"))
        self.qb_s.setText(_translate("Form", "S"))
        self.qb_x.setText(_translate("Form", "X"))
        self.qb_e.setText(_translate("Form", "E"))
        self.qb_r.setText(_translate("Form", "R"))
        self.qb_t.setText(_translate("Form", "T"))
        self.qb_y.setText(_translate("Form", "Y"))
        self.qb_u.setText(_translate("Form", "U"))
        self.qb_i.setText(_translate("Form", "I"))
        self.qb_d.setText(_translate("Form", "D"))
        self.qb_o.setText(_translate("Form", "O"))
        self.qb_p.setText(_translate("Form", "P"))
        self.qb_f.setText(_translate("Form", "F"))
        self.qb_g.setText(_translate("Form", "G"))
        self.qb_h.setText(_translate("Form", "H"))
        self.qb_j.setText(_translate("Form", "J"))
        self.qb_k.setText(_translate("Form", "K"))
        self.qb_l.setText(_translate("Form", "L"))
        self.qb_cc.setText(_translate("Form", "Ç"))
        self.qb_b.setText(_translate("Form", "B"))
        self.qb_c.setText(_translate("Form", "C"))
        self.qb_v.setText(_translate("Form", "V"))
        self.qb_m.setText(_translate("Form", "M"))
        self.qb_n.setText(_translate("Form", "N"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QDialog()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
